# Namespaces s√£o usados para organizar e isolar recursos no cluster
# Comando: kubectl create namespace <nome>
#
# Para criar todos os namespaces: kubectl apply -f base/namespaces.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: fast-2025

---
apiVersion: v1
kind: Namespace
metadata:
  name: getting-started

---
apiVersion: v1
kind: Namespace
metadata:
  name: flask-app

---
apiVersion: v1
kind: Namespace
metadata:
  name: init-container
