---
# Service para expor a aplicação Flask
apiVersion: v1
kind: Service
metadata:
  name: flask-hostname
  namespace: flask-app
spec:
  type: NodePort  # Tipo NodePort para acesso externo ao cluster
  selector:
    app: flask-hostname  # Seleciona os pods com este label
  ports:
    - protocol: TCP
      port: 80  # Porta do serviço
      targetPort: 5000  # Porta do container
